#!/bin/bash

# https://stackoverflow.com/a/5230306/1007638
option=

printf %s\\n "$@"


# # options may be followed by one colon to indicate they have a required argument
# if ! options=$(getopt -o d: -l dest: -- "$@")
# then
#     # something went wrong, getopt will put out an error message for us
#     exit 1
# fi

# eval set -- "$options"
# unset options

# while [ $# -gt 0 ]
# do
#     case "$1" in
#     -o|--opt) option=$2 ; shift;;
#     (--) shift; break;;
#     (-*) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
#     (*) break;;
#     esac
#     shift
# done

# echo "you said ${option}"

